# Generated by Django 4.1.7 on 2023-02-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duid', models.CharField(max_length=9)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(max_length=100)),
                ('PoCRN', models.CharField(max_length=100)),
                ('PrCRN', models.CharField(max_length=100)),
                ('elec', models.CharField(max_length=100)),
            ],
        ),
    ]
