# Generated by Django 4.1.7 on 2023-02-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
